apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "hello-world.fullname" . }}
  labels:
    {{- include "hello-world.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.rollout.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "hello-world.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hello-world.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "hello-world.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
{{- if .Values.smeeRelay.enabled }}
        - name: smee-relay
          image: "{{ .Values.smeeRelay.image.repository }}:{{ .Values.smeeRelay.image.tag }}"
          imagePullPolicy: {{ .Values.smeeRelay.image.pullPolicy }}
{{- with .Values.smeeRelay.env }}
          env:
{{- if .smeeUrlSecret }}
            - name: SMEE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .smeeUrlSecret.name }}
                  key: {{ .smeeUrlSecret.key }}
{{- else if .smeeUrl }}
            - name: SMEE_URL
              value: "{{ .smeeUrl }}"
{{- end }}
{{- if .target }}
            - name: SMEE_TARGET
              value: "{{ .target }}"
{{- end }}
{{- end }}
{{- end }}
  strategy:
    canary:
      {{- with .Values.rollout.strategy.canary.trafficRouting }}
      trafficRouting:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.rollout.strategy.canary.steps }}
      steps:
        {{- toYaml . | nindent 8 }}
      {{- end }}
